-module(gametypes).
%% spawn_entity => SPAWN
%% kill_entity => KILL
%% list_entites => LIST
-record(messages, {
            hello = 0,
            welcome = 1,
            spawn_entity = 2,
            despawn = 3,
            move = 4,
            lootmove = 5,
            aggro = 6,
            attack = 7,
            hit = 8,
            hurt = 9,
            health = 10,
            chat = 11,
            loot = 12,
            equip = 13,
            drop = 14,
            teleport = 15,
            damage = 16,
            population = 17,
            kill_entity = 18,
            list_entities = 19,
            who = 20,
            zone = 21,
            destroy = 22,
            hp = 23,
            blink = 24,
            open = 25,
            check = 26}).
